"""add raw_data to scraped_groups

Revision ID: 0dd9a36ecbd3
Revises: 89e6a44b62b1
Create Date: 2026-04-24 22:27:54.262354
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd9a36ecbd3'
down_revision = '89e6a44b62b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scraped_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_data', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scraped_groups', schema=None) as batch_op:
        batch_op.drop_column('raw_data')
    # ### end Alembic commands ###
