"""add subscriptions and promo codes

Revision ID: 89e6a44b62b1
Revises: 20260423_0009
Create Date: 2026-04-24 17:55:36.413742
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e6a44b62b1'
down_revision = '20260423_0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_codes_code'), 'promotion_codes', ['code'], unique=True)
    op.create_table('promotion_code_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_request_id', sa.Integer(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promotion_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_request_id'], ['subscription_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_code_id', 'tg_user_id', name='uq_promo_code_user')
    )
    op.create_index(op.f('ix_promotion_code_redemptions_tg_user_id'), 'promotion_code_redemptions', ['tg_user_id'], unique=False)
    
    with op.batch_alter_table('subscription_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('promo_code_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_subscription_requests_promo_code_id', 'promotion_codes', ['promo_code_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subscription_requests_promo_code_id', type_='foreignkey')
        batch_op.drop_column('promo_code_id')
        batch_op.drop_column('expires_at')
    
    op.drop_index(op.f('ix_promotion_code_redemptions_tg_user_id'), table_name='promotion_code_redemptions')
    op.drop_table('promotion_code_redemptions')
    op.drop_index(op.f('ix_promotion_codes_code'), table_name='promotion_codes')
    op.drop_table('promotion_codes')
    # ### end Alembic commands ###
