export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#006193",
        "on-primary-fixed-variant": "#004b73",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eef0ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#cce5ff",
        "on-primary": "#ffffff",
        "surface-dim": "#d2d9f4",
        "background": "#faf8ff",
        "on-primary-container": "#fdfcff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-variant": "#dae2fd",
        "secondary-container": "#d0e1fb",
        "tertiary-container": "#af6100",
        "surface-container-high": "#e2e7ff",
        "primary-container": "#007bb9",
        "on-surface": "#131b2e",
        "inverse-primary": "#92ccff",
        "outline-variant": "#bfc7d2",
        "surface-tint": "#006497",
        "surface-bright": "#faf8ff",
        "tertiary-fixed": "#ffdcc2",
        "on-primary-fixed": "#001d31",
        "on-secondary-container": "#54647a",
        "on-tertiary-fixed": "#2e1500",
        "on-error": "#ffffff",
        "tertiary": "#8b4c00",
        "tertiary-fixed-dim": "#ffb77a",
        "on-tertiary-container": "#fffbff",
        "on-surface-variant": "#3f4850",
        "surface-container-highest": "#dae2fd",
        "on-tertiary-fixed-variant": "#6d3a00",
        "surface": "#faf8ff",
        "secondary": "#505f76",
        "error": "#ba1a1a",
        "surface-container": "#eaedff",
        "inverse-surface": "#283044",
        "outline": "#6f7881",
        "secondary-fixed": "#d3e4fe",
        "on-background": "#131b2e",
        "primary-fixed-dim": "#92ccff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "base": "8px",
        "container-padding": "32px",
        "stack-md": "16px"
      },
      fontFamily: {
        "body-md": ["Noto Kufi Arabic", "Inter", "sans-serif"],
        "headline-xl": ["Noto Kufi Arabic", "Inter", "sans-serif"],
        "label-sm": ["Noto Kufi Arabic", "Inter", "sans-serif"],
        "headline-lg": ["Noto Kufi Arabic", "Inter", "sans-serif"],
        "body-lg": ["Noto Kufi Arabic", "Inter", "sans-serif"],
        "headline-md": ["Noto Kufi Arabic", "Inter", "sans-serif"],
        "label-md": ["Noto Kufi Arabic", "Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
}
